name = "social-analyzer"
main = "app.js"
compatibility_date = "2023-01-01"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "echo \"No build step required for this project\""
watch_dir = "./public"